# Generated by Django 4.1 on 2024-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bngjobs",
            name="address",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="hydjobs",
            name="address",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="vizagjobs",
            name="address",
            field=models.CharField(max_length=256),
        ),
    ]
